# Generated by Django 2.2.5 on 2022-11-28 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cozmessages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cozmessage',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
