# Generated by Django 2.2.5 on 2022-11-28 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cozmessages', '0002_cozmessage_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cozmessage',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
