# Generated by Django 3.0 on 2022-11-29 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cozmessages', '0003_auto_20221128_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cozmessage',
            name='roomname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='cozmessage',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
